[package]
name = "medialibrary-browser"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "medialibrary_browser_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.2", features = [] }
tauri-plugin-opener = "2.5.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4.26"
tauri-plugin-fs = "2.4.4"
tauri-plugin-log = "2.7.1"

#tauri-plugin-medialibrary = { version = "0.12.0" }
#[target.'cfg(all(unix, not(target_os = "android")))'.dependencies]
#tauri-plugin-medialibrary = { version = "0.12.0", features = ["xdg"] }

# [target.'cfg(windows)'.dependencies]
# tauri-plugin-medialibrary = { version = "0.12.0", features = ["thumb_cache"] }

# for development (you have to comment the above lines)
[target.'cfg(all(unix, target_os = "android"))'.dependencies]
tauri-plugin-medialibrary = { path = "../../tauri-plugin-medialibrary"  }

[target.'cfg(all(unix, not(target_os = "android")))'.dependencies]
tauri-plugin-medialibrary = { path = "../../tauri-plugin-medialibrary", features = ["amt"] }

[target.'cfg(windows)'.dependencies]
tauri-plugin-medialibrary = { path = "../../tauri-plugin-medialibrary", features = ["thumb_cache"] }

[patch.crates-io]
allmytoes = { git = "https://gitlab.com/dlehmeier/allmytoes"}
